spring.application.name=resource-server

spring.datasource.url=jdbc:postgresql://localhost:5432/librarydb
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8060